### ISSUE TITLE
Off by one indexing error

### ISSUE THREAD

**Issue by JorinRBM** [Buroni/booksoup#3]
Hey, great tool!
You may have an off by one error for indexing the month vs the day of the month [here](https://github.com/Buroni/booksoup/blob/c6081f1d80e71b2871bffb9296f1531ab855cb31/booksoup/FbTime.py#L83).
`date_str = date_arr[2]+"-"+self.__pad(list(calendar.month_name).index(date_arr[1]))`
The 1 used to index date_arr at the end of this line may need to be a 0.

**Comment by JorinRBM** [comment]
The error I am getting is this:
`$ python ./demo_interaction_timeline.py

Wednesday, September 29 2010 at 3:00pm PDT, data_arr = [u'September', u'29', u'2010']

Traceback (most recent call last):
  File "./demo_interaction_timeline.py", line 15, in <module>
    conversation = me.load_conversation(108)
  File "/booksoup/booksoup/BookSoup.py", line 36, in load_conversation
    contact = Conversation(os.path.join(self.__path, "messages", str(search_name)+".html"), interval=interval)
  File "/booksoup/booksoup/Conversation.py", line 22, in __init__
    self.messages.append(Message(m.find("span", class_="user").text, self.__fbt.span_meta_to_date(span.text, interval), span.text, m.next_sibling.text))
  File "/booksoup/booksoup/FbTime.py", line 84, in span_meta_to_date
    date_str = date_arr[2]+"-"+self.__pad(list(calendar.month_name).index(date_arr[1]))
ValueError: u'29' is not in list`

**Comment by Buroni** [comment]
H @JorinRBM , thanks for raising the issue. It seems that the dates are written differently in the US data dump (month-day-year). I've added a check to re-arrange the `date_arr` in `FBTime.py`, if you continue having problems with it please let me know!

**Comment by Buroni** [comment]
@JorinRBM I just had a look at your fork, and saw that you've actually made a lot of improvements to the timeline functionality by yourself. When you're happy with your changes, could you submit a PR on this repo?
